spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  context: annotation-config
  datasource:
    url: jdbc:h2:file:./data/sample
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  expirationTime: 3600000
  secret: asdsalqrk1232115dfas@!#!@sds
logging:
  file:
    name: logs/log
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'