spring:
  h2:
    console:
      enabled:true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: false
    defer-datasource-initialization: true
  security:
    user:
      name: admin
      password: admin
